### ISSUE TITLE
Definir el look and feel de la plataforma

### ISSUE THREAD

**Issue by ortegacmanuel** [Redeemy/redeemy#46]
Hasta ahora hemos trabajado y realizado muchos cambios en look and feel de la platforma y el estado actual es poco consistente. Tenemos un backend-API ya bastante solido con autenticación y que nos permitiría trabajar de forma rápida en nuevas funcionalidades. Pero antes de pasar a trabajar en funcionalidades deberíamos trabajar en definir que plantilla y el look and feel general que vamos a tener en la plaforma.

**Comment by ortegacmanuel** [comment]
- Saviti
web: https://themeforest.net/item/savity-charity-fundraising-bootstrap-html-template/21521823
demo: http://preview.themeforest.net/item/savity-charity-fundraising-bootstrap-html-template/full_screen_preview/21521823

- Charitus
web: https://xoothemes.com/item/charitus-donation-non-profit-charity-bootstrap-template/
demo: http://charitus-html.xoothemes.com/index.html

- CharityPress
web: https://themeforest.net/item/charitypress-charity-fundraising-html-template/21328253
demo: http://demo.xpeedstudio.com/html/charitypress/index.html

- Charitify
web: https://themeforest.net/item/charitify-ngocharityfundraising-html-template/21884830
demo: http://preview.themeforest.net/item/charitify-ngocharityfundraising-html-template/full_screen_preview/21884830

Vosotros tenéis algunas plantillas que os gusten? 

Mi preferida es Charitify, es Bootstrap 4. Lo conversamos, decidimos y nos ponemos a ello?

**Comment by leoneloliveros** [comment]
Me encantan están opciones, yo había mandado una por slack. Pero definitivamente estas son mejores opciones. Me gusta CharityPress, en realidad me gustan casi todas menos la Saviti.

**Comment by ortegacmanuel** [comment]
Vamos adelante con Charitify!
